// Package dedao implements the read-only Dedao web API client.
//
// Code in this file is generated data ported verbatim from the reference Python
// implementation's constant sets. Redaction policy must not drift between the
// two, so the sets were extracted mechanically rather than retyped.

package dedao

// sensitiveKeys are response keys stripped from every payload.
var sensitiveKeys = map[string]struct{}{
	"_sid":               {},
	"csrftoken":          {},
	"dd_article_token":   {},
	"m3u8_token":         {},
	"odob_article_token": {},
	"security_token":     {},
	"token":              {},
}

// sensitiveQueryKeys are url query parameters stripped from emitted urls.
var sensitiveQueryKeys = map[string]struct{}{
	"access_token": {},
	"auth_key":     {},
	"sign":         {},
	"volcsecret":   {},
}

// sensitiveMediaKeys are playback/DRM keys never exposed to an agent.
var sensitiveMediaKeys = map[string]struct{}{
	"a_media_id":           {},
	"amr_etag":             {},
	"amr_url":              {},
	"bitrate_1080":         {},
	"bitrate_1080_audio":   {},
	"bitrate_480":          {},
	"bitrate_480_audio":    {},
	"bitrate_720":          {},
	"bitrate_720_audio":    {},
	"caption":              {},
	"etag":                 {},
	"ld_flv":               {},
	"live_cover_m3u8":      {},
	"media_files":          {},
	"media_url":            {},
	"mp3_play_url":         {},
	"mp3_url":              {},
	"play_dd_url":          {},
	"play_url":             {},
	"playback_url":         {},
	"source_url":           {},
	"track_info":           {},
	"trackinfo":            {},
	"trial_listen_end_url": {},
	"video_audio":          {},
	"video_cover_m3u8":     {},
	"vtt_caption":          {},
}

// audiobookSafeFields is the allowlist audiobook metadata is filtered to.
var audiobookSafeFields = map[string]struct{}{
	"activity_name":          {},
	"agency":                 {},
	"agency_detail":          {},
	"alias_id":               {},
	"audio_detail":           {},
	"audio_id":               {},
	"audio_price":            {},
	"audio_summary":          {},
	"audio_type":             {},
	"author":                 {},
	"available_buy":          {},
	"avatar":                 {},
	"book_author":            {},
	"book_count":             {},
	"book_intro":             {},
	"book_list":              {},
	"book_shelf_status":      {},
	"button_type":            {},
	"can_given_count":        {},
	"can_share":              {},
	"card":                   {},
	"card_id":                {},
	"card_type":              {},
	"collection":             {},
	"consume_num":            {},
	"count":                  {},
	"cover":                  {},
	"created_at":             {},
	"days":                   {},
	"desc":                   {},
	"description":            {},
	"detail":                 {},
	"disclaimer":             {},
	"duration":               {},
	"end_time":               {},
	"enid":                   {},
	"expire_time":            {},
	"free_begin_time":        {},
	"free_end_time":          {},
	"free_maximum":           {},
	"given_card_count":       {},
	"has_play_auth":          {},
	"icon":                   {},
	"id":                     {},
	"id_str":                 {},
	"image":                  {},
	"in_bookrack":            {},
	"intro":                  {},
	"is_buy":                 {},
	"is_expire":              {},
	"is_free":                {},
	"is_limit_free":          {},
	"is_play_later":          {},
	"is_subscribed":          {},
	"is_vip":                 {},
	"is_vip_gived":           {},
	"learn_count":            {},
	"learn_count_desc":       {},
	"limit_free":             {},
	"list":                   {},
	"name":                   {},
	"odob_audio_detail_list": {},
	"one_sentence_summary":   {},
	"origin_price":           {},
	"package_pid":            {},
	"package_ptype":          {},
	"package_title":          {},
	"paytime":                {},
	"play_count":             {},
	"press":                  {},
	"price":                  {},
	"price_desc":             {},
	"privilege":              {},
	"product_id":             {},
	"product_id_str":         {},
	"product_list":           {},
	"product_type":           {},
	"progress":               {},
	"publish_time":           {},
	"quality":                {},
	"rank":                   {},
	"rank_desc":              {},
	"rank_name":              {},
	"rank_number":            {},
	"rank_type":              {},
	"reader_icon":            {},
	"reader_name":            {},
	"right":                  {},
	"rights":                 {},
	"save_price":             {},
	"selected":               {},
	"sole":                   {},
	"source_id":              {},
	"source_name":            {},
	"source_type":            {},
	"status":                 {},
	"sub_title":              {},
	"summary":                {},
	"surplus_time":           {},
	"tag":                    {},
	"title":                  {},
	"topic_encode_id":        {},
	"topic_id":               {},
	"topic_id_str":           {},
	"topic_summary":          {},
	"total":                  {},
	"total_count":            {},
	"trial_duration":         {},
	"trial_listen_tips":      {},
	"update_tips":            {},
	"updated_at":             {},
	"user":                   {},
	"user_max_buy_count":     {},
	"vip_end_time":           {},
	"week_count":             {},
}
